# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: 62966960+elnicomaldonado@users.noreply.github.com
author_name: elnicomaldonado
contract_name: algo_rewards_contract
deployment_language: python
preset_name: starter
project_name: AlgoRewards

